apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carts
  annotations:
    github.com/project-slug: gy-org/carts
    backstage.io/kubernetes-label-selector: 'app=carts'
  description: carts created
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  # dependsOn:
  #   - resource:crossplane-eks-demo-05